/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import org.apache.commons.lang3.StringUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityDir;
import model.Community;
import model.Company;
import model.CompanyDirectory;
import model.CustomerDirectory;
import model.DeliveryBoyDirectory;
import model.UserAuthenticationDirectory;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author 91961
 */
public class CityAdminPanel extends javax.swing.JPanel {

    private CityDir cityDirectory;
    private JSplitPane splitPane;
    private CustomerDirectory customerDirectory;
    private CompanyDirectory companyDirectory;
    private Community community;
    private UserAuthenticationDirectory userauthenticationdirectory;
    private DeliveryBoyDirectory deliveryBoyDirectory;
    private String selectedCityName;
    private String companyName;
    private String companyType;
    private int empCount;
    
    /**
     * Creates new form CompanyEntityAdminPanel
     */
    public CityAdminPanel() {
        initComponents();
    }

    public CityAdminPanel(String cityName, CityDir cityDirectory, UserAuthenticationDirectory userauthenticationdirectory, JSplitPane splitPane) {
        initComponents();
        this.cityDirectory = cityDirectory;
        this.splitPane = splitPane;        
        this.userauthenticationdirectory = userauthenticationdirectory;
        this.selectedCityName = cityName;
        
        ButtonGroup g1 = new ButtonGroup();
        
        g1.add(radioPrivate);
        g1.add(radioPublic);
    }

    /**
     * Populate the table cities rows from the arrayList.
     */
//    private void populateCities() {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        model.setRowCount(0);
//        for (City city : cityDirectory.getCityDir()) {
//            Object[] row = new Object[1];
//            row[0] = city.getCityName();
//            model.addRow(row);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        viewButton1 = new javax.swing.JButton();
        updateButton2 = new javax.swing.JButton();
        deleteButton3 = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioPublic = new javax.swing.JRadioButton();
        radioPrivate = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jTable5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Company Name", "Company Type", "Company Employee Count"
            }
        ));
        jTable5.setShowHorizontalLines(true);
        jTable5.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable5);

        viewButton1.setText("View");
        viewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton1ActionPerformed(evt);
            }
        });

        updateButton2.setText("Update");
        updateButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton2ActionPerformed(evt);
            }
        });

        deleteButton3.setText("Delete");
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Company Name:");

        jLabel2.setText("Company Type:");

        jLabel3.setText("Employee Count:");

        radioPublic.setText("Public");
        radioPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPublicActionPerformed(evt);
            }
        });

        radioPrivate.setText("Private");

        jButton1.setText("Company Admin CRUD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(viewButton1)
                                .addGap(28, 28, 28)
                                .addComponent(updateButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioPublic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioPrivate))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCount)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteButton3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(285, 285, 285)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton2)
                    .addComponent(deleteButton3)
                    .addComponent(viewButton1))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioPublic)
                            .addComponent(radioPrivate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(jButton1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButton1ActionPerformed
        // TODO add your handling code here:

        for (City city : cityDirectory.getCityDir()) {
            if (city.getCityName().equalsIgnoreCase(selectedCityName)) {
                if (city.getCompanyDirectory() == null) {
                    List<Company> communityList = new ArrayList<>();
                    populateCompanies(communityList);
                } else {
                    populateCompanies(city.getCompanyDirectory().getCompanyDirectoryList());
                }
                break;
            }
        }
    }//GEN-LAST:event_viewButton1ActionPerformed

    /**
     * Populate the table rows from the arrayList.
     */
    private void populateCompanies(List<Company> companyList) {
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        for (Company company : companyList) {
            Object[] row = new Object[3];
            row[0] = company.getCompanyName();
            row[1] = company.getCompanyType();
            row[2] = company.getCompanyEmployeeCount();
            model.addRow(row);
        }
    }


    private void updateButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable5.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        String selectedCompanyName = (String) model.getValueAt(selectedRowIndex, 0);

        String companyName = model.getValueAt(selectedRowIndex, 0).toString();
        String companyType = model.getValueAt(selectedRowIndex, 1).toString();
       
        long companyEmployeeCount = Long.parseLong(model.getValueAt(selectedRowIndex, 2).toString());
        String newCompanyName;
        while (true) {
            newCompanyName = JOptionPane.showInputDialog(null, "Enter the company name", companyName);
            if (StringUtils.isNotEmpty(newCompanyName)) {
                break;
            }
        }
        String newCompanyType;
        while (true) {
            newCompanyType = JOptionPane.showInputDialog(null, "Enter the company type", companyType);
            if (StringUtils.isNotEmpty(newCompanyType)) {
                break;
            }
        }
        String newCompanyEmployeeCount;
        while (true) {
            newCompanyEmployeeCount = JOptionPane.showInputDialog(null, "Enter the company employee count ", companyEmployeeCount);
            if (StringUtils.isNotEmpty(newCompanyEmployeeCount)) {
                break;
            }
        }

        model.setValueAt(newCompanyName, selectedRowIndex,0);
        model.setValueAt(newCompanyType, selectedRowIndex,1);
        model.setValueAt(newCompanyEmployeeCount, selectedRowIndex,2);

        for (City city
                : cityDirectory.getCityDir()) {
            if (city.getCityName().equalsIgnoreCase(selectedCityName)) {
                for (Company company : city.getCompanyDirectory().getCompanyDirectoryList()) {
                    if (company.getCompanyName().equalsIgnoreCase(selectedCompanyName)) {
                        company.setCompanyName(newCompanyName);
                        company.setCompanyType(newCompanyType);
                        company.setCompanyType(newCompanyEmployeeCount);
                        break;
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(this,
                "Company Record is Updated");
    }//GEN-LAST:event_updateButton2ActionPerformed

    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable5.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }       

        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        int rowToModel = 0;
        rowToModel = jTable5.convertRowIndexToModel(selectedRowIndex);
        model.removeRow(rowToModel);

        for (City city : cityDirectory.getCityDir()) {
            if (city.getCityName().equalsIgnoreCase(selectedCityName)) {
                city.getCompanyDirectory().deleteCompany(selectedRowIndex);
                populateCompanies(city.getCompanyDirectory().getCompanyDirectoryList());
                break;
            }
        }
        JOptionPane.showMessageDialog(this, "Company is deleted");
    }//GEN-LAST:event_deleteButton3ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        companyName = txtName.getText();
        empCount = Integer.parseInt(txtCount.getText());

        if(!companyName.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Name should have only alphabets.");
            return;
        }

        if(companyName.length() == 0) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.");
            return;
        }

        //Radio buttons
        String companyType = "";
        if(radioPrivate.isSelected() == true) {
            companyType = "Private";
        }
        else if(radioPublic.isSelected() == true){
            companyType = "Public";
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select a company type.");
            return;
        }
        
        for (City city : cityDirectory.getCityDir()) {
            if (city.getCityName().equalsIgnoreCase(selectedCityName)) {
                //city.getCompanyDirectory().deleteCompany(selectedRowIndex);
                Company c = city.getCompanyDirectory().addNewCompany();
                
                c.setCompanyName(companyName);
                c.setCompanyType(companyType);
                c.setCompanyEmployeeCount(empCount);
                
                JOptionPane.showMessageDialog(this, "New company is created.");
                
                populateCompanies(city.getCompanyDirectory().getCompanyDirectoryList());
                break;
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void radioPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPublicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPublicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CompanyAdminCRUDPanel cp = new CompanyAdminCRUDPanel(selectedCityName, companyName, cityDirectory, companyDirectory, userauthenticationdirectory, splitPane);
        splitPane.setRightComponent(cp);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton deleteButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JRadioButton radioPrivate;
    private javax.swing.JRadioButton radioPublic;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtName;
    private javax.swing.JButton updateButton2;
    private javax.swing.JButton viewButton1;
    // End of variables declaration//GEN-END:variables
}
