/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityDir;
import model.Community;
import model.CompanyDirectory;
import model.CustomerDirectory;
import model.DeliveryBoy;
import model.DeliveryBoyDirectory;
import model.Ordermgt;
import model.UserAuthenticationDirectory;

/**
 *
 * @author hrish
 */
public class DeliveryAdminModifyPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAdminPanel
     */
    private String deliveryBoyName;
    private long emergencyContactNumber;
    private String qualificaton;
    private int yearOfDeliveryExperience;
    private Community community;
    private DeliveryBoyDirectory deliveryBoyDirectory;
    private DeliveryAdminMainPanel delAdmin;
    private CityDir cityDir;
    private String cityName;
    private String companyName;
    private CustomerDirectory customerDirectory;
    private CompanyDirectory companyDirectory;
    private UserAuthenticationDirectory userauthenticationdirectory;
    private JSplitPane splitPane;
    private JSplitPane jSplitPane1;
    private String role;
    private Ordermgt orderManagement;

    public DeliveryAdminModifyPanel(Community community, DeliveryBoyDirectory deliveryBoyDirectory, CityDir cityDir, String cityName, String companyName, CustomerDirectory customerDirectory, CompanyDirectory companyDirectory, UserAuthenticationDirectory userauthenticationdirectory, JSplitPane splitPane, JSplitPane jSplitPane1, String role, Ordermgt orderManagement) {
        initComponents();

        this.community = community;
        this.deliveryBoyDirectory = deliveryBoyDirectory;
        this.delAdmin = delAdmin;
        this.cityDir = cityDir;
        this.cityName = cityName;
        this.companyName = companyName;
        this.customerDirectory = customerDirectory;
        this.companyDirectory = companyDirectory;
        this.userauthenticationdirectory = userauthenticationdirectory;
        this.splitPane = splitPane;
        this.jSplitPane1 = jSplitPane1;
        this.role = role;
        this.orderManagement = orderManagement;

        ButtonGroup buttonGroup = new ButtonGroup();

        buttonGroup.add(radioHighSchool);
        buttonGroup.add(radioUniversity);

        populateDeliveryBoyTable();
    }

    private void populateDeliveryBoyTable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

        DefaultTableModel model = (DefaultTableModel) tblDeliveryBoys.getModel();
        model.setRowCount(0);

        if (deliveryBoyDirectory.getDeliveryBoyList() != null) {
            for (DeliveryBoy d : deliveryBoyDirectory.getDeliveryBoyList()) {

                Object[] row = new Object[11];
                //row[0] = house;
                row[0] = d.getDeliveryBoyName();
                row[1] = d.getQualificaton();
                row[2] = d.getYearOfDeliveryExperience();
                row[3] = d.getEmergencyContactNumber();

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryBoys = new javax.swing.JTable();
        updateDeliveryBoy = new javax.swing.JButton();
        btnDeleteDeliveryBoy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radioHighSchool = new javax.swing.JRadioButton();
        radioUniversity = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmergencyContact = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jLabel4.setText("Years of Experience:");

        txtExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienceActionPerformed(evt);
            }
        });

        jLabel5.setText("Delivery Boy Name:");

        tblDeliveryBoys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery Boy Name", "Qualification", "Years of Experience", "Emergency Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeliveryBoys.setPreferredSize(new java.awt.Dimension(904, 638));
        jScrollPane1.setViewportView(tblDeliveryBoys);

        updateDeliveryBoy.setText("Update Delivery Boy");
        updateDeliveryBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeliveryBoyActionPerformed(evt);
            }
        });

        btnDeleteDeliveryBoy.setText("Delete Delivery Boy");
        btnDeleteDeliveryBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDeliveryBoyActionPerformed(evt);
            }
        });

        jLabel3.setText("Qualification:");

        radioHighSchool.setText("High School");

        radioUniversity.setText("University");

        jLabel6.setText("Emergency Contact:");

        txtEmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyContactActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteDeliveryBoy, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioHighSchool)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioUniversity))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(updateDeliveryBoy, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(62, 62, 62)
                                .addComponent(txtEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteDeliveryBoy)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioHighSchool)
                    .addComponent(radioUniversity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateDeliveryBoy)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void updateDeliveryBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeliveryBoyActionPerformed
        // TODO add your handling code here:

        if (txtName.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mandatory name field is empty");
            return;
        }

        if (!txtName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Name field should only have alphabets");
            return;
        }

        if (txtEmergencyContact.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mandatory emergency contact name field is empty");
            return;
        }

        if (txtExperience.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mandatory emergency contact name field is empty");
            return;
        }

        deliveryBoyName = txtName.getText();
        yearOfDeliveryExperience = Integer.parseInt(txtEmergencyContact.getText());
        emergencyContactNumber = Long.parseLong(txtExperience.getText());

        //Radio buttons
        if (radioHighSchool.isSelected() == true) {
            qualificaton = "High School";
        } else if (radioUniversity.isSelected() == true) {
            qualificaton = "University";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a qualificaton.");
        }

        int selectedRowIndex = tblDeliveryBoys.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a delivery boy to update.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDeliveryBoys.getModel();
        String selectedDeliveryBoy = (String) model.getValueAt(selectedRowIndex, 0);

        ArrayList<DeliveryBoy> delBoyDir = (ArrayList) deliveryBoyDirectory.getDeliveryBoyList();

        for (DeliveryBoy d : delBoyDir) {

            if (d.getDeliveryBoyName().equalsIgnoreCase(selectedDeliveryBoy)) {

                d.setAvailability(true);
                d.setDeliveryBoyName(deliveryBoyName);
                d.setEmergencyContactNumber(emergencyContactNumber);
                d.setQualificaton(qualificaton);
                d.setYearOfDeliveryExperience(yearOfDeliveryExperience);
            }
        }

        JOptionPane.showMessageDialog(this, "Delivery Boy updated!");

        txtName.setText("");
        txtEmergencyContact.setText("");
        txtExperience.setText("");
        radioHighSchool.setEnabled(false);
        radioUniversity.setEnabled(false);

        populateDeliveryBoyTable();
    }//GEN-LAST:event_updateDeliveryBoyActionPerformed

    private void btnDeleteDeliveryBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeliveryBoyActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblDeliveryBoys.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a delivery boy.");
            return;
        }

        DefaultTableModel model;
        model = (DefaultTableModel) tblDeliveryBoys.getModel();
        String deliveryBoy = (String) model.getValueAt(selectedRowIndex, 0);

        ArrayList<DeliveryBoy> delBoyDir = (ArrayList) deliveryBoyDirectory.getDeliveryBoyList();

        for (DeliveryBoy d : delBoyDir) {

            if (d.getDeliveryBoyName().equalsIgnoreCase(deliveryBoy)) {

                deliveryBoyDirectory.deleteDeliveryBoy(d);

                populateDeliveryBoyTable();
                JOptionPane.showMessageDialog(this, "Delivery Boy Deleted!");
                break;
            }
        }

    }//GEN-LAST:event_btnDeleteDeliveryBoyActionPerformed

    private void txtEmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyContactActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DeliveryAdminMainPanel d = new DeliveryAdminMainPanel(cityDir, cityName, companyName, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory, jSplitPane1, role, orderManagement);
        if (role == null) {
            splitPane.setRightComponent(d);
        } else {
            jSplitPane1.setRightComponent(d);
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDeliveryBoy;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioHighSchool;
    private javax.swing.JRadioButton radioUniversity;
    private javax.swing.JTable tblDeliveryBoys;
    private javax.swing.JTextField txtEmergencyContact;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtName;
    private javax.swing.JButton updateDeliveryBoy;
    // End of variables declaration//GEN-END:variables
}
