/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.UserAuthenticationDirectory;
import javax.swing.JSplitPane;
import javax.swing.JOptionPane;
import model.CityDir;
import model.Community;
import model.CompanyDirectory;
import model.CustomerDirectory;
import model.DeliveryBoyDirectory;
import model.Ordermgt;
import model.UserAuthentication;

/**
 *
 * @author Abhishek
 */
public class LoginJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private CityDir cityDirectory;
    private Community community;
    private CustomerDirectory customerDirectory;
    private CompanyDirectory companyDirectory;
    private UserAuthenticationDirectory userauthenticationdirectory;
    private DeliveryBoyDirectory deliveryBoyDirectory;
    private Ordermgt orderManagement;
    private String companyName;
    private String usertype;
    private String cityName;

    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel() {
//        initComponents();
    }

    public LoginJPanel(CityDir cityDirectory, Ordermgt orderManagement, Community community, CustomerDirectory customerDirectory, CompanyDirectory companyDirectory, UserAuthenticationDirectory userauthenticationdirectory, JSplitPane splitPane, DeliveryBoyDirectory deliveryBoyDirectory) {
        initComponents();
        String imgDir = System.getProperty("user.dir")+"/src/main/java/IMAGES/";
        loginLabel.setIcon(new ImageIcon(new ImageIcon(imgDir+"login.png").getImage().getScaledInstance(1000, 300, Image.SCALE_DEFAULT)));
        welcomeLabel.setIcon(new ImageIcon(new ImageIcon(imgDir+"hello.gif").getImage().getScaledInstance(250, 350, Image.SCALE_DEFAULT)));
        roadLabel.setIcon(new ImageIcon(new ImageIcon(imgDir+"road.png").getImage().getScaledInstance(1300, 300, Image.SCALE_DEFAULT)));
        this.cityDirectory = cityDirectory;
        this.community = community;
        this.customerDirectory = customerDirectory;
        this.companyDirectory = companyDirectory;
        this.userauthenticationdirectory = userauthenticationdirectory;
        this.splitPane = splitPane;
        this.deliveryBoyDirectory = deliveryBoyDirectory;
        this.orderManagement = orderManagement;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameJLabel1 = new javax.swing.JLabel();
        passwordLabel2 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        loginButton1 = new javax.swing.JButton();
        passwordTextField2 = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        roadLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        usernameJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameJLabel1.setText("Username");

        passwordLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel2.setText("Password");

        loginButton1.setBackground(new java.awt.Color(71, 43, 29));
        loginButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        loginButton1.setForeground(new java.awt.Color(255, 255, 255));
        loginButton1.setText("Login");
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });

        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 73, Short.MAX_VALUE)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(passwordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(loginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(roadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        // TODO add your handling code here:

        if (usernameTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "UserName is empty");
            return;
        }

        if (passwordTextField2.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Password text field is empty");
            return;
        }

        boolean flag = false;
        for (UserAuthentication userAuthentication : userauthenticationdirectory.getUserAuthenticationList()) {
            if (userAuthentication.getUserName().equalsIgnoreCase(usernameTextField1.getText())
                    && userAuthentication.getPassword().equalsIgnoreCase(passwordTextField2.getText())) {
                usertype = userAuthentication.getUserType();
                companyName = userAuthentication.getCompanyName();
                cityName = userAuthentication.getCityName();
                flag = true;
            }
        }

        if (flag && usertype.equalsIgnoreCase("Customer")) {
//            JOptionPane.showMessageDialog(this, "Login is successfully done for customer");
            MainCustomerJPanel mainCustomerJPanel = new MainCustomerJPanel(cityDirectory, usernameTextField1.getText(), orderManagement, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(mainCustomerJPanel);
            
            splitPane.setLeftComponent(new LogoutPane(cityDirectory, orderManagement, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory));
        } else if (flag && usertype.equalsIgnoreCase("DeliveryBoy")) {
//            JOptionPane.showMessageDialog(this, "Login is successfully done for Delivery Boy");
            MainDeliveryBoyJPanel mainDeliveryBoyJPanel = new MainDeliveryBoyJPanel(community, usernameTextField1.getText(), customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(mainDeliveryBoyJPanel);
        } else if (flag && usertype.equalsIgnoreCase("CompanyAdmin")) {
//            JOptionPane.showMessageDialog(this, "Login is successfully done for Company Admin");
            MainCompanyAdminJPanel mainCompanyAdminPanel = new MainCompanyAdminJPanel(cityName, companyName, cityDirectory, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(mainCompanyAdminPanel);
        } else if (flag && usertype.equalsIgnoreCase("OrderAdmin")) {
//            JOptionPane.showMessageDialog(this, "Login is successfully done for Order Admin");
            MainOrderAdminJPanel mainOrderAdminJPanel = new MainOrderAdminJPanel(orderManagement, cityDirectory, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(mainOrderAdminJPanel);
        } else if (flag && usertype.equalsIgnoreCase("SuperAdmin")) {
//            JOptionPane.showMessageDialog(this, "Login is successfully done for Super Admin");
            SuperAdminPanel supAdmin = new SuperAdminPanel(cityDirectory, orderManagement, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(supAdmin);
        } else if (flag && usertype.equalsIgnoreCase("CityAdmin")) {
            JOptionPane.showMessageDialog(this, "Login is successfully done for City Admin");
            CityAdminPanel supAdmin = new CityAdminPanel(cityName, cityDirectory, userauthenticationdirectory, splitPane);
            splitPane.setRightComponent(supAdmin);
        } else if (flag && usertype.equalsIgnoreCase("DeliveryAdmin")) {
            JOptionPane.showMessageDialog(this, "Login is successfully done for Delivery Admin");
            DeliveryAdminMainPanel delAdmin = new DeliveryAdminMainPanel(cityDirectory, cityName, companyName, community, customerDirectory, companyDirectory, userauthenticationdirectory, splitPane, deliveryBoyDirectory);
            splitPane.setRightComponent(delAdmin);
        } else if (flag && usertype.equalsIgnoreCase("InventoryAdmin")) {
            JOptionPane.showMessageDialog(this, "Login is successfully done for Inventory Admin");
            InventoryAdminPanel invAdmin = new InventoryAdminPanel(cityName, companyName, cityDirectory, splitPane, userauthenticationdirectory);
            splitPane.setRightComponent(invAdmin);
        }
    }//GEN-LAST:event_loginButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel2;
    private javax.swing.JPasswordField passwordTextField2;
    private javax.swing.JLabel roadLabel;
    private javax.swing.JLabel usernameJLabel1;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
